1. Import the numpy package under the name `np`

In [2]:
import numpy as np

2. Create a null vector of size 10

In [5]:
np.zeros((10), dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

3. Create a null vector of size 10 but the fifth value which is 1

In [13]:
a=np.zeros((10), dtype=int)
a[4]=True
a

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

4. Create a vector with values ranging from 10 to 49

In [14]:
np.arange(10,50, dtype=int)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

5. Create a 3x3 matrix with values ranging from 0 to 8 

In [21]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

6. Find indices of non-zero elements from [1,2,0,0,4,0]

In [27]:
b=np.array([1,2,0,0,4,0])
b[np.nonzero(b)]

array([1, 2, 4])

In [28]:
c=np.array([1,2,0,0,4,0])
c[c != 0]

array([1, 2, 4])

In [3]:
c=np.array([1,2,0,0,4,0])
np.nonzero(c)

(array([0, 1, 4], dtype=int64),)

7. Create a 3x3 identity matrix

In [30]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

8. Create a 3x3x3 array with random values

In [58]:
np.random.seed(seed=500)
np.random.random((3,3,3))

array([[[0.69367953, 0.06171699, 0.6666116 ],
        [0.55920894, 0.08511062, 0.39241906],
        [0.49707753, 0.33214907, 0.34233845]],

       [[0.36563683, 0.85062578, 0.44849744],
        [0.31647204, 0.36173317, 0.45072243],
        [0.91526806, 0.45995858, 0.27367946]],

       [[0.91749612, 0.45953222, 0.54459121],
        [0.69069037, 0.83083808, 0.63590931],
        [0.64981717, 0.95375833, 0.56995437]]])

9. Create a 10x10 array with random values and find the minimum and maximum values

In [75]:
np.random.seed(seed=500)
d=np.random.random((10,10))
d=d*100
print(np.round(d))

[[69.  6. 67. 56.  9. 39. 50. 33. 34. 37.]
 [85. 45. 32. 36. 45. 92. 46. 27. 92. 46.]
 [54. 69. 83. 64. 65. 95. 57. 64.  4. 75.]
 [86. 49. 23. 50. 14. 17. 10. 24. 66. 60.]
 [66. 92. 96. 82. 13. 77. 57. 75. 27. 89.]
 [28. 25. 44. 73. 11.  6. 90. 63. 93. 91.]
 [10. 74. 75. 34. 99. 59. 21. 78. 82. 69.]
 [67. 80. 98. 34. 99. 35. 99. 58. 74. 72.]
 [84. 51. 76. 24. 62. 96. 29.  3. 26. 94.]
 [87. 54. 11. 91. 92. 78. 69. 23. 36. 73.]]


In [78]:
print(np.min(np.round(d)))

3.0


In [80]:
print(np.max(np.round(d)))

99.0


10. Create a random vector of size 30 and find the mean value

In [85]:
np.random.seed(seed=500)
e=np.random.random((30))
print(e)
np.mean(e)

[0.69367953 0.06171699 0.6666116  0.55920894 0.08511062 0.39241906
 0.49707753 0.33214907 0.34233845 0.36563683 0.85062578 0.44849744
 0.31647204 0.36173317 0.45072243 0.91526806 0.45995858 0.27367946
 0.91749612 0.45953222 0.54459121 0.69069037 0.83083808 0.63590931
 0.64981717 0.95375833 0.56995437 0.6352015  0.03646224 0.74912676]


0.5248761085226363

11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 

In [93]:
f=np.diag([1,2,3,4],k=-1)
print(f)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


12. Normalize a 5x5 random matrix

In [109]:
np.random.seed(seed=500)
g=np.random.random((5,5))
g=((g-np.mean(g))/np.std(g))
print(g)

[[ 0.80173298 -1.98814577  0.68223817  0.20809551 -1.88487162]
 [-0.52821957 -0.06619148 -0.79428905 -0.74930675 -0.6464531 ]
 [ 1.49459213 -0.28065442 -0.86349732 -0.66368631 -0.27083194]
 [ 1.77996368 -0.23005778 -1.05241059  1.7897997  -0.23193999]
 [ 0.1435637   0.78853698  1.40723679  0.54669904  0.60809703]]


13. How to find common values between two arrays?

In [17]:
np.random.seed(seed=500)
k1=np.random.randint(1,10, size=5)
k2=np.random.randint(1,10, size=5)
print(k1)
print(k2)
print(np.intersect1d(k1, k2))

[8 2 2 9 8]
[2 2 6 3 3]
[2]


14. Create a random vector of size 10 and sort it 

In [112]:
np.random.seed(seed=500)
g=np.random.random((10))
np.sort(g)

array([0.06171699, 0.08511062, 0.33214907, 0.34233845, 0.36563683,
       0.39241906, 0.49707753, 0.55920894, 0.6666116 , 0.69367953])

15. Create random vector of size 10 and replace the maximum value by 0

In [125]:
np.random.seed(seed=500)
h=np.random.random((10))
h=np.round(h*100)
print(h)
h[h == np.max(h)] = 0
print(h)

[69.  6. 67. 56.  9. 39. 50. 33. 34. 37.]
[ 0.  6. 67. 56.  9. 39. 50. 33. 34. 37.]


In [20]:
np.random.seed(seed=500)
h=np.random.random((10))
h=np.round(h*100)
print(h)
h[np.argmax(h)] = 0
print(h)

[69.  6. 67. 56.  9. 39. 50. 33. 34. 37.]
[ 0.  6. 67. 56.  9. 39. 50. 33. 34. 37.]


16. Subtract the mean of each row of a matrix

In [155]:
np.random.seed(seed=500)
i=np.random.random((3,3))
i=i*100
print(np.round(i))
i2=i-np.mean(i, axis=1)
print(i2)

[[69.  6. 67.]
 [56.  9. 39.]
 [50. 33. 34.]]
[[ 21.96768214 -28.38625462  27.60899125]
 [  8.52062312 -26.04689159   0.18973719]
 [  2.30748218  -1.34304642  -4.81832324]]


17. How to get the n largest values of an array (n=5)

In [36]:
z = np.arange(10000)
np.random.shuffle(z)
n = 5
z[np.argsort(z)[-n:]]
np.partition(z,-n)[-n:]

array([9995, 9996, 9997, 9998, 9999])

In [27]:
z = np.arange(10000)
np.random.shuffle(z)
n = 5
print(z[np.argsort(z)])
print(z[np.argpartition(-z,n)[:n]])

[   0    1    2 ... 9997 9998 9999]
[9999 9998 9997 9996 9995]


18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 

In [43]:
np.random.seed(seed=500)
j=np.random.randint(10, size=(5,3))

k=np.where(j>4, j**2, j)
print(j)
print(k)

[[7 1 1]
 [8 7 1]
 [1 5 9]
 [2 2 3]
 [6 8 7]]
[[49  1  1]
 [64 49  1]
 [ 1 25 81]
 [ 2  2  3]
 [36 64 49]]
