In [2]:
import numpy as np

In [4]:
a=np.random.random((10,4))

In [7]:
print(a)

[[0.42566525 0.08771976 0.99387308 0.80472974]
 [0.07703801 0.65999428 0.32401327 0.05943412]
 [0.08556904 0.50811409 0.79122183 0.51633098]
 [0.53208892 0.63085918 0.10130617 0.97499653]
 [0.92813223 0.59577146 0.30940802 0.30140551]
 [0.93941529 0.60066452 0.68614712 0.60319014]
 [0.25725647 0.67217232 0.38692018 0.59698706]
 [0.678138   0.3460487  0.58548469 0.76797489]
 [0.29709628 0.8275101  0.27933587 0.93463585]
 [0.76155388 0.39244117 0.67652189 0.00566951]]


NameError: name 'shape' is not defined